export const ADD_TAG = 'ADD_TAG';
export const CLEAR_TAGS = 'CLEAR_TAGS';
export const INITIALIZE_NEW_RECIPE = 'INITIALIZE_NEW_RECIPE';
export const MODIFY_RECIPE = 'MODIFY_RECIPE';
export const CLEAR_RECIPE = 'CLEAR_RECIPE';